### ISSUE TITLE
Include article's post date

### ISSUE THREAD

**Issue by nicksaemenes** [jedfoster/Roughdraft#55]
Please include article's post date. 
A number of the articles on roughdraft.io use relative language such as "At this time" or "When this article was written," but it isn't always clear when that was. It would be helpful in such cases to include the article's post date somewhere on the page. 
I am a huge fan of the simple and clean design of this site and I understand that more elements on the page detracts from the aesthetic. That being said, I am hoping you'll agree that the benefits of this function (knowing the date) outweighs those of form (clean design). 
You're consideration of this proposal is appreciated. 
Thanks

**Comment by blackfalcon** [comment]
:+1: this. For revisions the initial post date should be there always and revision dates, maybe.
