### ISSUE TITLE
The font doesn't display Umlauts correctly

### ISSUE THREAD

**Issue by staeff** [jedfoster/Roughdraft#56]
http://staeff.roughdraft.io/639889449053035b35d2-data-munging-for-hackathon-project-party-haus
Just a minor thing, but the font you chose does not display special non-ascii chars correctly. See link above.

**Comment by jedfoster** [comment]
Where? Headings? Or body content? I took a look with and without the webfonts and and I don't see any incorrect characters. 

Could you please post a screenshot?

![screen shot 2015-03-28 at 9 42 36 am](https://cloud.githubusercontent.com/assets/79984/6881894/dc452d12-d52e-11e4-8bf7-0e5b38fe5f84.png)
